MAP = """
#########################
#. RLL  B      R        #
#LL   RRRRRLLL  MLLLLRRR#
#L  LL   MMM    M LLLL  #
#RR LLLLM   M  M  RR    #
#     MM  R  MM   MMRRRR#
# L LLM L  B  LLRM    LL#
# R LM    LLLLL  MRRRRRL#
#     LLL R  RR M   LL  #
#  LRRRR   LLL  M   LL $#
#########################
"""

SPRITE_SIZE = 32

MAP_START = '.'
TREASURE = '$'
MAP_WALL = '#'
RIVER = 'M'
AGENT = 'A'
ROCK = 'R'
LOG = 'L'
BEE = 'B'
EMPTY = ' '
SWORD = 'S'
PICKAXE = 'P'

TREASURE_INDICATOR = 'X'

ACTION_UP = 'U'
ACTION_DOWN = 'D'
ACTION_LEFT = 'L'
ACTION_RIGHT = 'R'
ACTION_PULL_UP = 'Pu'
ACTION_PULL_DOWN = 'Pd'
ACTION_PULL_RIGHT = 'Pr'
ACTION_PULL_LEFT = 'Pl'
ACTION_PICKAXE = 'P'
ACTION_SWORD = 'S'
ACTIONS = [
    ACTION_UP, ACTION_DOWN, ACTION_LEFT, ACTION_RIGHT,
    ACTION_PICKAXE, ACTION_SWORD,
    ACTION_PULL_UP, ACTION_PULL_DOWN, ACTION_PULL_RIGHT, ACTION_PULL_LEFT
]

ACTION_MOVES = {
    ACTION_RIGHT: (SPRITE_SIZE, 0),
    ACTION_LEFT: (-SPRITE_SIZE, 0),
    ACTION_UP: (0, SPRITE_SIZE),
    ACTION_DOWN: (0, -SPRITE_SIZE),
    ACTION_PULL_RIGHT: (SPRITE_SIZE, 0),
    ACTION_PULL_LEFT: (-SPRITE_SIZE, 0),
    ACTION_PULL_UP: (0, SPRITE_SIZE),
    ACTION_PULL_DOWN: (0, -SPRITE_SIZE),
    ACTION_PICKAXE: (0, 0),
    ACTION_SWORD: (0, 0)
}

AGENT_POSITION_IN_RADAR = 4

INDEX_TOP = 9
INDEX_RIGHT = 10
INDEX_DOWN = 11
INDEX_LEFT = 12

RADAR_ACTION_INDEX = {
    ACTION_UP: 3,
    ACTION_DOWN: 5,
    ACTION_LEFT: 1,
    ACTION_RIGHT: 7,
    ACTION_PULL_UP: 3,
    ACTION_PULL_DOWN: 5,
    ACTION_PULL_LEFT: 1,
    ACTION_PULL_RIGHT: 7,
    ACTION_PICKAXE: AGENT_POSITION_IN_RADAR,
    ACTION_SWORD: AGENT_POSITION_IN_RADAR
}

FAVORITE_ACTIONS_BY_TREASURE_POSITION = {
    0: [ACTION_UP, ACTION_LEFT],
    1: [ACTION_LEFT],
    2: [ACTION_DOWN, ACTION_LEFT],
    3: [ACTION_UP],
    5: [ACTION_DOWN],
    6: [ACTION_UP, ACTION_RIGHT],
    7: [ACTION_RIGHT],
    8: [ACTION_DOWN, ACTION_RIGHT],
}

FAVORITE_ACTION_BONUS = 0.1

REWARD_DEFAULT = -1

FILE_AGENT = 'agent.golddigger'

BEE_SPEED = 1.0
BEE_INTERVAL = 50

RESTART_AUTOMATICALLY = True