MAP = """
#########################
#.  RLL  B      R       #
#LL   RRRRRLLL  MLLLLRRR#
#L  LL   MMM    M LLLL  #
#RR LLLLM   M  M  RR    #
#     MM  R  MM   MMRRRR#
# L LLM L  B  LLRM    LL#
# R LM    LLLLL  MRRRRRL#
#     LLL R  RR M   LL  #
#   RRRR   LLL  M   LL $#
#########################
"""

SPRITE_SIZE = 32

MAP_START = '.'
TREASURE = '$'
MAP_WALL = '#'
RIVER = 'M'
AGENT = 'A'
ROCK = 'R'
LOG = 'L'
BEE = 'B'
EMPTY = ' '
SWORD = 'S'
PICKAXE = 'P'

ACTION_UP = 'U'
ACTION_DOWN = 'D'
ACTION_LEFT = 'L'
ACTION_RIGHT = 'R'
ACTION_PULL_UP = 'Pu'
ACTION_PULL_DOWN = 'Pd'
ACTION_PULL_RIGHT = 'Pr'
ACTION_PULL_LEFT = 'Pl'
ACTION_PICKAXE = 'P'
ACTION_SWORD = 'S'
ACTIONS = [
    ACTION_UP, ACTION_DOWN, ACTION_LEFT, ACTION_RIGHT,
    ACTION_PICKAXE, ACTION_SWORD,
    ACTION_PULL_UP, ACTION_PULL_DOWN, ACTION_PULL_RIGHT, ACTION_PULL_LEFT
]

ACTION_MOVES = {
    ACTION_UP: (0, SPRITE_SIZE),
    ACTION_DOWN: (0, -SPRITE_SIZE),
    ACTION_LEFT: (-SPRITE_SIZE, 0),
    ACTION_RIGHT: (SPRITE_SIZE, 0),
    ACTION_PULL_UP: (0, SPRITE_SIZE),
    ACTION_PULL_DOWN: (0, -SPRITE_SIZE),
    ACTION_PULL_LEFT: (-SPRITE_SIZE, 0),
    ACTION_PULL_RIGHT: (SPRITE_SIZE, 0),
    ACTION_PICKAXE: (0, 0),
    ACTION_SWORD: (0, 0)
    ## TODO switch_tool ?
}

RADAR_ACTION_INDEX = {
    ACTION_UP: 2,
    ACTION_DOWN: 8,
    ACTION_LEFT: 4,
    ACTION_RIGHT: 6,
    ACTION_PULL_UP: 2,
    ACTION_PULL_DOWN: 8,
    ACTION_PULL_RIGHT: 4,
    ACTION_PULL_LEFT: 6,
    ACTION_PICKAXE: 5,
    ACTION_SWORD: 5
}

REWARD_DEFAULT = -1

FILE_AGENT = 'agent.golddigger'

BEE_SPEED = 1.0
BEE_INTERVAL = 50

RESTART_AUTOMATICALLY = True
